apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binarycalculator
  template:
    metadata:
      labels:
        app: binarycalculator
    spec:
      containers:
      - name: binarycalculator
        image: us-central1-docker.pkg.dev/project-ea4dece2-e8a6-4c87-a19/sofe3980u/binarycalculator:latest
        ports:
        - containerPort: 8080
